ci:
    autoupdate_schedule: monthly
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml # checks for correct yaml syntax for github actions ex.
        args: [--unsafe]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --extend-ignore=E402]
      - id: ruff-format
  - repo: https://github.com/crate-ci/typos
    rev: v1.23.6
    hooks:
      - id: typos
        files: \.(py|md|rst|yaml|toml)
        # empty to do not write fixes
        args: []
        exclude: pyproject.toml
# mypy will force you to type your code ;)
#   - repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.11.1
#     hooks:
#       - id: mypy
#         language: python
#         args: [--strict, --ignore-missing-imports]
#         additional_dependencies: ['types-requests', 'types-PyYAML']
#         exclude: docs/source/conf.py
